### ISSUE TITLE
DynamicBasicBlock

### ISSUE THREAD

**Issue by tommiekerssies** [GAIA-vision/GAIA-ssl#5]
Hi, I was wondering whether by any chance you already implemented support for DynamicBasicBlock?
I want to train a small supernet and extract subnets with flops in the RN18 group, but I can't compare them because RN18 uses basicblocks.

**Comment by NickChang97** [comment]
Sorry, we don't support for DynamicBasicBlock, but with our DynamicConv, it seems not hard to implement.

**Comment by tommiekerssies** [comment]
Thanks for your response. I have implemented it myself, was very easy indeed. Please see my PR: https://github.com/GAIA-vision/GAIA-cv/pull/4

**Comment by NickChang97** [comment]
Really thanks for this PR.
